"use client";

import * as React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Download, Copy, FileText, CheckCircle2 } from "lucide-react";
import ReactMarkdown from "react-markdown";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

interface LabReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  reportMarkdown: string;
  experimentName: string;
}

export function LabReportModal({ isOpen, onClose, reportMarkdown, experimentName }: LabReportModalProps) {
  const [copied, setCopied] = React.useState(false);
  const [downloading, setDownloading] = React.useState(false);
  const reportRef = React.useRef<HTMLDivElement>(null);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(reportMarkdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDownloadPDF = async () => {
    if (!reportRef.current) return;
    try {
      setDownloading(true);
      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        backgroundColor: "#0a0f1a", // Deep dark background to match theme
        logging: false,
      });

      const imgData = canvas.toDataURL("image/jpeg", 1.0);
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

      pdf.addImage(imgData, "JPEG", 0, 0, pdfWidth, pdfHeight);
      pdf.save(`Lab_Report_${experimentName.replace(/\s+/g, '_')}.pdf`);
    } catch (error) {
      console.error("PDF generation failed:", error);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 text-white font-sans">
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-lab-dark/80 backdrop-blur-sm"
          />

          {/* Modal Container */}
          <motion.div
            initial={{ scale: 0.95, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.95, opacity: 0, y: 20 }}
            className="relative w-full max-w-4xl max-h-[90vh] bg-lab-card border border-lab-border rounded-2xl shadow-2xl flex flex-col overflow-hidden"
          >
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-lab-border bg-lab-dark">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-brand-teal/20 rounded-lg border border-brand-teal/30">
                  <FileText className="w-6 h-6 text-brand-teal" />
                </div>
                <div>
                  <h2 className="text-xl font-heading font-bold text-white leading-none mb-1">
                    Official Laboratory Report
                  </h2>
                  <p className="text-sm text-gray-400">Generated by AI Tutor Cleo</p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-4 py-2 bg-lab-highlight border border-lab-border rounded-lg text-sm font-medium hover:bg-white/10 transition-colors"
                >
                  {copied ? <CheckCircle2 className="w-4 h-4 text-brand-teal" /> : <Copy className="w-4 h-4 text-gray-300" />}
                  <span className="hidden sm:inline">{copied ? "Copied!" : "Copy"}</span>
                </button>
                <button
                  onClick={handleDownloadPDF}
                  disabled={downloading}
                  className="flex items-center gap-2 px-4 py-2 bg-brand-teal text-lab-dark rounded-lg text-sm font-semibold hover:bg-brand-tealAccent transition-colors disabled:opacity-50"
                >
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">{downloading ? "Generating PDF..." : "Download PDF"}</span>
                </button>
                <button
                  onClick={onClose}
                  className="ml-2 p-2 hover:bg-lab-highlight rounded-lg transition-colors text-gray-400 hover:text-white"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Markdown Content Area */}
            <div className="flex-1 overflow-y-auto p-8 bg-lab-dark scroll-smooth">
              <div
                ref={reportRef}
                className="max-w-3xl mx-auto prose prose-invert prose-brand prose-headings:font-heading prose-a:text-brand-teal prose-code:text-brand-purple"
              >
                {reportMarkdown ? (
                  <ReactMarkdown>{reportMarkdown}</ReactMarkdown>
                ) : (
                  <div className="flex flex-col items-center justify-center p-20 text-gray-500 gap-4">
                    <FileText className="w-12 h-12 opacity-50" />
                    <p>No report data available to display.</p>
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
